import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Janny Zhao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/janny-photo.png" />
      </head>
      <div className="flex justify-center max-w-screen-md">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </div>
    </html>
  );
}
